artifact_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


base_model_preparation:
  root_dir: artifacts/base_model_preparation
  base_model_path: artifacts/base_model_preparation/base_model.h5
  updated_base_model_path: artifacts/base_model_preparation/base_model_updated.h5
  
callback_preparation:
  root_dir: artifacts/callback_preparation
  tensorboard_root_log_dir: artifacts/callback_preparation/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/callback_preparation/checkpoint_dir/model.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5