from cnnProject.componets.data_ingestion import DataIngestion
from cnnProject.componets.base_model_preparation import BaseModelPreparation
from cnnProject.componets.callback_preparation import CallbackPreparation